package com.hand.activity.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "rent_activity_zzw")
public class ActivityZzw extends BaseDTO {

     public static final String FIELD_ACTIVITY_ID = "activityId";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_CREATE_DATA = "createData";
     public static final String FIELD_PEOPLE = "people";
     public static final String FIELD_START_RELEASE_DATA = "startReleaseData";
     public static final String FIELD_END_RELEASE_DATA = "endReleaseData";
     public static final String FIELD_STATUS = "status";
     public static final String FIELD_CONTENT = "content";
     public static final String FIELD_ROLE_NAME = "roleName";
     public static final String FIELD_ACTIVITY_EMPLOYEE = "activityEmployee";
     public static final String FIELD_MONEY = "money";


     @Id
     @GeneratedValue
     private Long activityId;

     @NotNull
     @Length(max = 50)
     private String name; //活动名称

     private Date createData; //创建日期

     @Length(max = 50)
     private String people; //创建人

     @NotNull
     @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
     private Date startReleaseData; //发布日期从

     @NotNull
     @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
     private Date endReleaseData; //发布日期到


     @Length(max = 50)
     private String status; //状态

     @NotNull
     @Length(max = 65535)
     private String content; //活动内容


     @Length(max = 50)
     private String roleName; //角色名称

     @NotNull
     @Length(max = 50)
     private String activityEmployee; //负责管理员工

     @NotNull
     private Double money; //活动金额


     public void setActivityId(Long activityId){
         this.activityId = activityId;
     }

     public Long getActivityId(){
         return activityId;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setCreateData(Date createData){
         this.createData = createData;
     }

     public Date getCreateData(){
         return createData;
     }

     public void setPeople(String people){
         this.people = people;
     }

     public String getPeople(){
         return people;
     }

     public void setStartReleaseData(Date startReleaseData){
         this.startReleaseData = startReleaseData;
     }

     public Date getStartReleaseData(){
         return startReleaseData;
     }

     public void setEndReleaseData(Date endReleaseData){
         this.endReleaseData = endReleaseData;
     }

     public Date getEndReleaseData(){
         return endReleaseData;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setContent(String content){
         this.content = content;
     }

     public String getContent(){
         return content;
     }

     public void setRoleName(String roleName){
         this.roleName = roleName;
     }

     public String getRoleName(){
         return roleName;
     }

     public void setActivityEmployee(String activityEmployee){
         this.activityEmployee = activityEmployee;
     }

     public String getActivityEmployee(){
         return activityEmployee;
     }

     public void setMoney(Double money){
         this.money = money;
     }

     public Double getMoney(){
         return money;
     }

     }
